<?xml version="1.0" encoding="utf-8"?><Database Name="Track_EmergencyCall_Contact" Class="AracTakip_UzakDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=78.189.180.28;Initial Catalog=Track_EmergencyCall_Contact;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Track_EmergencyCall_ContactConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Locking" Member="Lockings">
    <Type Name="Locking">
      <Column Name="S_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sirket_ADI" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Kullanıcı_ADI" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Kullanici_SIFRE" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Sirket_PORT" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Track_PortPlaka" Member="Track_PortPlakas">
    <Type Name="Track_PortPlaka">
      <Column Name="PlakaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PortNumber" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Plaka" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Track_LocationInf" Member="Track_LocationInfs">
    <Type Name="Track_LocationInf">
      <Column Name="LocationInf" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PortNumber" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Plaka" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LatPos" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LonPos" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="Speed" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="EmergencyCall" Type="System.String" DbType="NChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>